from __future__ import annotations


WHOOP_BUNDLE = {
    "schema_version": 1,
    "source": "whoop-local",
    "pulled_at": "2026-09-01T20:30:00Z",
    "window_start": "2026-08-25T00:00:00Z",
    "window_end": "2026-09-01T20:30:00Z",
    "collections": {
        "recovery": {
            "privacy_mode": "structured",
            "count": 1,
            "records": [{
                "cycle_id": 101,
                "sleep_id": "sleep-101",
                "updated_at": "2026-09-01T13:00:00Z",
                "score_state": "SCORED",
                "recovery_score": 73,
                "resting_heart_rate": 52,
                "hrv_rmssd_milli": 68.4,
                "spo2_percentage": 97.1,
                "skin_temp_celsius": 33.2,
                "user_id": 999,
            }],
            "has_more": False,
            "pages_fetched": 1,
        },
        "sleep": {
            "privacy_mode": "structured",
            "count": 1,
            "records": [{
                "id": "sleep-101",
                "cycle_id": 101,
                "start": "2026-09-01T04:00:00Z",
                "end": "2026-09-01T12:00:00Z",
                "updated_at": "2026-09-01T13:00:00Z",
                "score_state": "SCORED",
                "nap": False,
                "sleep_performance_percentage": 84,
                "sleep_consistency_percentage": 77,
                "sleep_efficiency_percentage": 91,
                "respiratory_rate": 14.2,
                "total_in_bed_time_milli": 28_800_000,
                "total_awake_time_milli": 2_592_000,
                "total_light_sleep_time_milli": 12_000_000,
                "total_slow_wave_sleep_time_milli": 7_000_000,
                "total_rem_sleep_time_milli": 7_208_000,
                "disturbance_count": 8,
                "user_id": 999,
            }],
            "has_more": False,
            "pages_fetched": 1,
        },
        "cycle": {
            "privacy_mode": "structured",
            "count": 1,
            "records": [{
                "id": 101,
                "start": "2026-09-01T12:00:00Z",
                "end": "2026-09-02T04:00:00Z",
                "updated_at": "2026-09-01T20:00:00Z",
                "score_state": "SCORED",
                "strain": 10.8,
                "average_heart_rate": 78,
                "max_heart_rate": 181,
                "kilojoule": 2140.5,
                "user_id": 999,
            }],
            "has_more": False,
            "pages_fetched": 1,
        },
        "workout": {
            "privacy_mode": "structured",
            "count": 1,
            "records": [{
                "id": "workout-101",
                "start": "2026-09-01T18:00:00Z",
                "end": "2026-09-01T19:15:00Z",
                "updated_at": "2026-09-01T19:20:00Z",
                "score_state": "SCORED",
                "sport_name": "Dance",
                "strain": 12.1,
                "average_heart_rate": 135,
                "max_heart_rate": 181,
                "kilojoule": 1234.5,
                "percent_recorded": 99.2,
                "distance_meter": 0,
                "altitude_gain_meter": 0,
                "zone_zero_milli": 1000,
                "zone_one_milli": 2000,
                "zone_two_milli": 3000,
                "zone_three_milli": 4000,
                "zone_four_milli": 5000,
                "zone_five_milli": 6000,
                "user_id": 999,
            }],
            "has_more": False,
            "pages_fetched": 1,
        },
        "body_measurement": {
            "privacy_mode": "structured",
            "count": 1,
            "records": [{
                "id": "current",
                "height_meter": 1.8288,
                "weight_kilogram": 90.7185,
                "max_heart_rate": 200,
            }],
            "has_more": False,
            "pages_fetched": 1,
        },
    },
}
